import { tokens } from '@emdash/theme';
import type { TokenReference } from '@emdash/theme';

/**
 * The complete host-owned theme boundary supported by `@emdash/chat-ui`.
 *
 * Measurement-coupled `--chat-type-*` and `--chat-*-pad-*` values are owned by
 * Chat UI's runtime configuration and intentionally do not belong in this map.
 */
export const chatHostProperties = {
  foreground: '--chat-fg',
  foregroundBody: '--chat-fg-body',
  foregroundMuted: '--chat-fg-muted',
  foregroundPassive: '--chat-fg-passive',
  background: '--chat-bg',
  backgroundSubtle: '--chat-bg-1',
  backgroundMuted: '--chat-bg-2',
  backgroundStrong: '--chat-bg-3',
  border: '--chat-border',
  userCardBackground: '--chat-user-card-bg',
  userCardBorder: '--chat-user-card-border',
  userCardBorderHover: '--chat-user-card-border-hover',
  mentionChipBackground: '--chat-mention-chip-bg',
  mentionChipForeground: '--chat-mention-chip-fg',
  mentionFileBackground: '--chat-mention-file-bg',
  mentionFileForeground: '--chat-mention-file-fg',
  mentionIssueBackground: '--chat-mention-issue-bg',
  mentionIssueForeground: '--chat-mention-issue-fg',
  mentionSymbolBackground: '--chat-mention-symbol-bg',
  mentionSymbolForeground: '--chat-mention-symbol-fg',
  mentionCustomBackground: '--chat-mention-custom-bg',
  mentionCustomForeground: '--chat-mention-custom-fg',
  diffAdded: '--chat-diff-added',
  diffDeleted: '--chat-diff-deleted',
  diffModified: '--chat-diff-modified',
  foregroundError: '--chat-fg-error',
  link: '--chat-link',
  userBubbleBackground: '--chat-bubble-user',
  userBubbleForeground: '--chat-bubble-user-fg',
  mentionBackground: '--chat-mention-bg',
  mentionForeground: '--chat-mention-fg',
  codeBackground: '--chat-code-bg',
  inlineCodeBackground: '--chat-code-inline-bg',
  tableHeaderBackground: '--chat-table-header-bg',
  planDone: '--chat-plan-done',
  planActive: '--chat-plan-active',
  fontSans: '--chat-font-sans',
  fontMono: '--chat-font-mono',
  radiusSmall: '--chat-radius-sm',
  radiusMedium: '--chat-radius-md',
  radiusLarge: '--chat-radius-lg',
  radiusExtraLarge: '--chat-radius-xl',
  radiusFull: '--chat-radius-full',
} as const;

export type ChatHostProperty = (typeof chatHostProperties)[keyof typeof chatHostProperties];
export type ChatHostTokenValues = Readonly<Record<ChatHostProperty, TokenReference>>;

/** Maps every host-owned Chat UI property to a canonical Theme Token Value. */
export function createChatHostTokenValues(): ChatHostTokenValues {
  return {
    [chatHostProperties.foreground]: tokens.foreground.default,
    [chatHostProperties.foregroundBody]: tokens.foreground.body,
    [chatHostProperties.foregroundMuted]: tokens.foreground.muted,
    [chatHostProperties.foregroundPassive]: tokens.foreground.passive,
    [chatHostProperties.background]: tokens.surface.role.paper.background,
    [chatHostProperties.backgroundSubtle]: tokens.surface.level.base.background,
    [chatHostProperties.backgroundMuted]: tokens.surface.level.base.hover,
    [chatHostProperties.backgroundStrong]: tokens.surface.level.base.selected,
    [chatHostProperties.border]: tokens.border.default,
    [chatHostProperties.userCardBackground]: tokens.surface.level.raised.background,
    [chatHostProperties.userCardBorder]: tokens.border.default,
    [chatHostProperties.userCardBorderHover]: tokens.border.muted,
    [chatHostProperties.mentionChipBackground]: tokens.surface.level.raised.hover,
    [chatHostProperties.mentionChipForeground]: tokens.foreground.default,
    [chatHostProperties.mentionFileBackground]: tokens.surface.level.raised.hover,
    [chatHostProperties.mentionFileForeground]: tokens.foreground.default,
    [chatHostProperties.mentionIssueBackground]: tokens.surface.tone.info.background,
    [chatHostProperties.mentionIssueForeground]: tokens.surface.tone.info.foreground,
    [chatHostProperties.mentionSymbolBackground]: tokens.surface.tone.info.background,
    [chatHostProperties.mentionSymbolForeground]: tokens.surface.tone.info.foreground,
    [chatHostProperties.mentionCustomBackground]: tokens.surface.level.raised.hover,
    [chatHostProperties.mentionCustomForeground]: tokens.foreground.default,
    [chatHostProperties.diffAdded]: tokens.feedback.success.foreground,
    [chatHostProperties.diffDeleted]: tokens.feedback.error.foreground,
    [chatHostProperties.diffModified]: tokens.feedback.warning.foreground,
    [chatHostProperties.foregroundError]: tokens.feedback.error.foreground,
    [chatHostProperties.link]: tokens.feedback.info.foreground,
    [chatHostProperties.userBubbleBackground]: tokens.surface.level.base.selected,
    [chatHostProperties.userBubbleForeground]: tokens.foreground.default,
    [chatHostProperties.mentionBackground]: tokens.surface.tone.info.background,
    [chatHostProperties.mentionForeground]: tokens.surface.tone.info.foreground,
    [chatHostProperties.codeBackground]: tokens.surface.level.sunken.background,
    [chatHostProperties.inlineCodeBackground]: tokens.surface.level.sunken.hover,
    [chatHostProperties.tableHeaderBackground]: tokens.surface.level.raised.background,
    [chatHostProperties.planDone]: tokens.feedback.success.foreground,
    [chatHostProperties.planActive]: tokens.feedback.warning.foreground,
    [chatHostProperties.fontSans]: tokens.typography.family.sans,
    [chatHostProperties.fontMono]: tokens.typography.family.mono,
    [chatHostProperties.radiusSmall]: tokens.radius.sm,
    [chatHostProperties.radiusMedium]: tokens.radius.md,
    [chatHostProperties.radiusLarge]: tokens.radius.lg,
    [chatHostProperties.radiusExtraLarge]: tokens.radius.xl,
    [chatHostProperties.radiusFull]: tokens.radius.full,
  };
}
