import { globalStyle, style } from '@vanilla-extract/css';

/** Rooted Adapter for syntax-token spans generated by Shiki. */
export const shikiTokensAdapter = style({});

globalStyle(`${shikiTokensAdapter} span`, {
  color: 'var(--shiki-light)',
});

globalStyle(`${shikiTokensAdapter}:where(.emdark *) span`, {
  color: 'var(--shiki-dark)',
});
