// Internal core RPC barrel: everything generic on the wire. Live endpoint
// kinds are composed on top by `../rpc`, which is the public `@emdash/wire/rpc`
// entry. The engine seam (`buildController`, `buildClient`, `./endpoint-kinds`)
// is deliberately kept out of this barrel.
export {
  blobSourceFromBytes,
  concatBytes,
  copyBytes,
  createBlobConsumer,
  createBlobProducer,
  createSingleUseDownloadHandle,
  createWireFile,
  isDownloadFileOpenResult,
  markDownloadFileOpen,
  normalizeUploadFile,
  type BlobConsumer,
  type BlobDownloadHandle,
  type BlobProducer,
  type BlobSource,
  type DownloadFileOpen,
  type FileLike,
  type ReadableStreamLike,
  type UploadFileValue,
  type WireFile,
} from './blob-channel';
export {
  createMutationId,
  eventStreamSnapshotDataSchema,
  liveCursorEntrySchema,
  liveCursorSchema,
  liveLogSnapshotDataSchema,
  liveSnapshotSchema,
  liveUpdateSchema,
  type EventStreamSnapshotData,
  type LiveAttachmentErrorContext,
  type LiveCursor,
  type LiveCursorEntry,
  type LiveLogSnapshotData,
  type LiveMutationInput,
  type LiveMutationResult,
  type LiveMutationSuccess,
  type LiveSnapshot,
  type LiveSource,
  type LiveSubscribeOptions,
  type LiveUpdate,
  type Mutator,
} from './channel';
export {
  isEventStreamClientHandle,
  isLiveJobClientHandle,
  isLiveLogClientHandle,
  isLiveModelClientHandle,
  type ClientOptions,
  type ContractClient,
  type EventStreamClientHandle,
  type EventStreamSubscribeOptions,
  type FileUploadCallOptions,
  type LiveClientHandle,
  type LiveJobClientHandle,
  type LiveJobStateFor,
  type LiveLogClientHandle,
  type LiveModelClientHandle,
  type MutationCallOptions,
  type ProcedureCallOptions,
} from './client';
export {
  connect,
  DEFAULT_CALL_TIMEOUT_MS,
  type AttachOptions,
  type CallOptions,
  type Connection,
  type ConnectOptions,
} from './connect';
export { isController, type CallMeta, type Controller, type ProcedureHandler } from './controller';
export {
  contractSymbol,
  defineContract,
  downloadFile,
  eventStream,
  fallible,
  isEndpointDef,
  liveJob,
  liveLog,
  liveModel,
  liveState,
  mutation,
  procedure,
  resourcedStream,
  uploadFile,
  wireFileMetaSchema,
  type Contract,
  type ContractDefinitions,
  type ContractEntry,
  type DownloadFileEndpointDef,
  type DownloadFileError,
  type DownloadFileInput,
  type DownloadFileMeta,
  type EndpointDef,
  type EndpointInput,
  type EndpointOutput,
  type EventStreamEndpointDef,
  type EventStreamEvent,
  type EventStreamKey,
  type JobError,
  type JobInput,
  type JobProgress,
  type JobResult,
  type LiveJobEndpointDef,
  type LiveLogEndpointDef,
  type LiveLogKey,
  type LiveModelDef,
  type LiveModelKey,
  type LiveModelMutationCtx,
  type LiveModelMutationHandler,
  type LiveModelMutations,
  type LiveModelStates,
  type LiveStateData,
  type LiveStateDef,
  type LiveStateKey,
  type MutationData,
  type MutationDef,
  type MutationError,
  type MutationInput,
  type ProcedureDef,
  type UploadFileEndpointDef,
  type UploadFileError,
  type UploadFileInput,
  type UploadFileResult,
} from './define';
export {
  isWireError,
  isWireMessage,
  serializeWireError,
  WireError,
  type SerializedWireError,
  type WireAttachMessage,
  type WireBlobChunkMessage,
  type WireBlobCloseMessage,
  type WireBlobEndMessage,
  type WireBlobErrorMessage,
  type WireBlobPullMessage,
  type WireCallMessage,
  type WireCancelMessage,
  type WireDetachMessage,
  type WireErrorCode,
  type WireFileMeta,
  type WireMessage,
  type WireResultMessage,
  type WireSnapshotMessage,
  type WireTopicErrorMessage,
  type WireTopicGapMessage,
  type WireTransport,
  type WireUpdateMessage,
} from './protocol';
export { serve, type ServeOptions } from './serve';
export { createWireSessionHub, type WireSessionHub } from './sessions';
export { encodeTopic, splitTopic } from './topics';
export {
  awaitWirePort,
  domPortTransport,
  exposeWireToWindows,
  memoryTransportPair,
  portTransport,
  reconnectingTransport,
  requestWirePort,
  streamTransport,
  type DomPortLike,
  type ExposeWireOptions,
  type IpcMainInvokeEventLike,
  type IpcMainLike,
  type IpcRendererLike,
  type MemoryTransportPair,
  type MessageChannelFactory,
  type MessagePortMainLike,
  type PortLike,
  type ReconnectFailureContext,
  type ReconnectingTransport,
  type ReconnectingTransportOptions,
  type WebContentsLike,
  type WindowLike,
} from './transports';
export { applyValidation, defaultValidatePolicy, type ValidatePolicy } from './validation';
