/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsIdRouteImport } from './routes/skills.$id'
import { Route as PromptsIdRouteImport } from './routes/prompts.$id'
import { Route as AutomationsIdRouteImport } from './routes/automations.$id'
import { Route as ApiSplatRouteImport } from './routes/api.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIdRoute = SkillsIdRouteImport.update({
  id: '/skills/$id',
  path: '/skills/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsIdRoute = PromptsIdRouteImport.update({
  id: '/prompts/$id',
  path: '/prompts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsIdRoute = AutomationsIdRouteImport.update({
  id: '/automations/$id',
  path: '/automations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/automations/$id': typeof AutomationsIdRoute
  '/prompts/$id': typeof PromptsIdRoute
  '/skills/$id': typeof SkillsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/automations/$id': typeof AutomationsIdRoute
  '/prompts/$id': typeof PromptsIdRoute
  '/skills/$id': typeof SkillsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/automations/$id': typeof AutomationsIdRoute
  '/prompts/$id': typeof PromptsIdRoute
  '/skills/$id': typeof SkillsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/$'
    | '/automations/$id'
    | '/prompts/$id'
    | '/skills/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/$' | '/automations/$id' | '/prompts/$id' | '/skills/$id'
  id:
    | '__root__'
    | '/'
    | '/api/$'
    | '/automations/$id'
    | '/prompts/$id'
    | '/skills/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSplatRoute: typeof ApiSplatRoute
  AutomationsIdRoute: typeof AutomationsIdRoute
  PromptsIdRoute: typeof PromptsIdRoute
  SkillsIdRoute: typeof SkillsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$id': {
      id: '/skills/$id'
      path: '/skills/$id'
      fullPath: '/skills/$id'
      preLoaderRoute: typeof SkillsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts/$id': {
      id: '/prompts/$id'
      path: '/prompts/$id'
      fullPath: '/prompts/$id'
      preLoaderRoute: typeof PromptsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations/$id': {
      id: '/automations/$id'
      path: '/automations/$id'
      fullPath: '/automations/$id'
      preLoaderRoute: typeof AutomationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSplatRoute: ApiSplatRoute,
  AutomationsIdRoute: AutomationsIdRoute,
  PromptsIdRoute: PromptsIdRoute,
  SkillsIdRoute: SkillsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
