import { defineCommandPaletteItem } from '@core/primitives/palette/api';
import {
  archiveTaskCommand,
  browserCopyUrlCommand,
  browserFocusUrlCommand,
  browserGoBackCommand,
  browserGoForwardCommand,
  browserOpenExternalCommand,
  browserReloadCommand,
  convertAutomationCommand,
  deleteSelectedTasksCommand,
  fileContentSearchCommand,
  gitFetchCommand,
  gitPullCommand,
  gitPushCommand,
  newConversationCommand,
  newConversationSplitRightCommand,
  newTerminalCommand,
  openBrowserCommand,
  pinTaskCommand,
  sidebarChangesCommand,
  sidebarConversationsCommand,
  sidebarFilesCommand,
  toggleRightSidebarCommand,
  toggleTerminalDrawerCommand,
  viewTerminalsCommand,
} from './commands';

export const TASK_COMMAND_PALETTE_ITEMS = [
  defineCommandPaletteItem({ command: newConversationCommand }),
  defineCommandPaletteItem({ command: newConversationSplitRightCommand }),
  defineCommandPaletteItem({ command: sidebarChangesCommand }),
  defineCommandPaletteItem({ command: sidebarConversationsCommand }),
  defineCommandPaletteItem({ command: sidebarFilesCommand }),
  defineCommandPaletteItem({ command: fileContentSearchCommand }),
  defineCommandPaletteItem({ command: viewTerminalsCommand }),
  defineCommandPaletteItem({ command: toggleTerminalDrawerCommand }),
  defineCommandPaletteItem({ command: toggleRightSidebarCommand }),
  defineCommandPaletteItem({ command: newTerminalCommand }),
  defineCommandPaletteItem({ command: openBrowserCommand }),
  defineCommandPaletteItem({ command: browserGoBackCommand }),
  defineCommandPaletteItem({ command: browserGoForwardCommand }),
  defineCommandPaletteItem({ command: browserReloadCommand }),
  defineCommandPaletteItem({ command: browserFocusUrlCommand }),
  defineCommandPaletteItem({ command: browserOpenExternalCommand }),
  defineCommandPaletteItem({ command: browserCopyUrlCommand }),
  defineCommandPaletteItem({ command: gitFetchCommand }),
  defineCommandPaletteItem({ command: gitPullCommand }),
  defineCommandPaletteItem({ command: gitPushCommand }),
  defineCommandPaletteItem({ command: pinTaskCommand }),
  defineCommandPaletteItem({ command: archiveTaskCommand }),
  defineCommandPaletteItem({ command: convertAutomationCommand }),
  defineCommandPaletteItem({ command: deleteSelectedTasksCommand }),
] as const;
