import { definePaletteItem } from '@core/primitives/palette/api';
import {
  archiveTaskCommand,
  browserCopyUrlCommand,
  browserFocusUrlCommand,
  browserGoBackCommand,
  browserGoForwardCommand,
  browserOpenExternalCommand,
  browserReloadCommand,
  convertAutomationCommand,
  deleteSelectedTasksCommand,
  fileContentSearchCommand,
  gitFetchCommand,
  gitPullCommand,
  gitPushCommand,
  newConversationCommand,
  newConversationSplitRightCommand,
  newTerminalCommand,
  openBrowserCommand,
  pinTaskCommand,
  sidebarChangesCommand,
  sidebarConversationsCommand,
  sidebarFilesCommand,
  toggleRightSidebarCommand,
  toggleTerminalDrawerCommand,
  viewTerminalsCommand,
} from './commands';

export const TASK_PALETTE_ITEMS = [
  definePaletteItem({ command: newConversationCommand, rank: 10 }),
  definePaletteItem({ command: newConversationSplitRightCommand, rank: 20 }),
  definePaletteItem({ command: sidebarChangesCommand, rank: 30 }),
  definePaletteItem({ command: sidebarConversationsCommand, rank: 40 }),
  definePaletteItem({ command: sidebarFilesCommand, rank: 50 }),
  definePaletteItem({ command: fileContentSearchCommand, rank: 55 }),
  definePaletteItem({ command: viewTerminalsCommand, rank: 60 }),
  definePaletteItem({ command: toggleTerminalDrawerCommand, rank: 70 }),
  definePaletteItem({ command: toggleRightSidebarCommand, rank: 80 }),
  definePaletteItem({ command: newTerminalCommand, rank: 90 }),
  definePaletteItem({ command: openBrowserCommand, rank: 100 }),
  definePaletteItem({ command: browserGoBackCommand, rank: 110 }),
  definePaletteItem({ command: browserGoForwardCommand, rank: 120 }),
  definePaletteItem({ command: browserReloadCommand, rank: 130 }),
  definePaletteItem({ command: browserFocusUrlCommand, rank: 140 }),
  definePaletteItem({ command: browserOpenExternalCommand, rank: 150 }),
  definePaletteItem({ command: browserCopyUrlCommand, rank: 160 }),
  definePaletteItem({ command: gitFetchCommand, rank: 170 }),
  definePaletteItem({ command: gitPullCommand, rank: 180 }),
  definePaletteItem({ command: gitPushCommand, rank: 190 }),
  definePaletteItem({ command: pinTaskCommand, rank: 200 }),
  definePaletteItem({ command: archiveTaskCommand, rank: 210 }),
  definePaletteItem({ command: convertAutomationCommand, rank: 220 }),
  definePaletteItem({ command: deleteSelectedTasksCommand, rank: 230 }),
] as const;
