//! Wire-format snapshots for the renderer ↔ Rust IPC contract.
//!
//! These tests pin the on-the-wire shape of each command so accidental
//! signature changes (renamed parameters, swapped types, modified responses)
//! produce a reviewable snapshot diff rather than silently breaking the
//! renderer. To accept a deliberate change: run `cargo insta review`.
//!
//! The bindings.ts snapshot covers the full TypeScript surface generated by
//! tauri-specta; the per-command JSON snapshots cover the actual values that
//! flow over `invoke`.

#[test]
fn greet_wire_format() {
    let response = emdash_dev::greeting::greet("world");
    let request_args = serde_json::json!({ "name": "world" });

    insta::assert_json_snapshot!("greet_request_args", request_args);
    insta::assert_snapshot!("greet_response_world", response);
}

#[test]
fn greet_trims_and_defaults_empty_name() {
    insta::assert_snapshot!("greet_empty_name", emdash_dev::greeting::greet(""));
    insta::assert_snapshot!("greet_whitespace_name", emdash_dev::greeting::greet("   "));
}

#[test]
fn bindings_ts_snapshot() {
    let path = format!("{}/ui/src/bindings.ts", env!("CARGO_MANIFEST_DIR"),);
    let content = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!("read {path}: {e} — run `cargo run --bin emdash-dev -- --export-bindings`")
    });
    insta::assert_snapshot!("bindings_ts", content);
}
