/**
 * Canonical author-facing Token References.
 *
 * Keep this tree literal: its built declaration is the navigation surface for
 * Token authors. CSS custom-property names are an implementation detail behind
 * these references.
 *
 * @example
 * ```ts
 * import { tokens } from '@emdash/theme';
 * import { style } from '@emdash/ui/styles';
 *
 * const mutedCopy = style({
 *   color: tokens.foreground.muted,
 *   marginBlockStart: tokens.space.step2,
 * });
 * ```
 */
export const tokens = {
  palette: {
    neutral: {
      step1: 'var(--em-neutral-1)',
      step2: 'var(--em-neutral-2)',
      step3: 'var(--em-neutral-3)',
      step4: 'var(--em-neutral-4)',
      step5: 'var(--em-neutral-5)',
      step6: 'var(--em-neutral-6)',
      step7: 'var(--em-neutral-7)',
      step8: 'var(--em-neutral-8)',
      step9: 'var(--em-neutral-9)',
      step10: 'var(--em-neutral-10)',
      step11: 'var(--em-neutral-11)',
      step12: 'var(--em-neutral-12)',
      contrast: 'var(--em-neutral-contrast)',
    },
    accent: {
      step1: 'var(--em-accent-1)',
      step2: 'var(--em-accent-2)',
      step3: 'var(--em-accent-3)',
      step4: 'var(--em-accent-4)',
      step5: 'var(--em-accent-5)',
      step6: 'var(--em-accent-6)',
      step7: 'var(--em-accent-7)',
      step8: 'var(--em-accent-8)',
      step9: 'var(--em-accent-9)',
      step10: 'var(--em-accent-10)',
      step11: 'var(--em-accent-11)',
      step12: 'var(--em-accent-12)',
      contrast: 'var(--em-accent-contrast)',
    },
    green: {
      step1: 'var(--em-green-1)',
      step2: 'var(--em-green-2)',
      step3: 'var(--em-green-3)',
      step4: 'var(--em-green-4)',
      step5: 'var(--em-green-5)',
      step6: 'var(--em-green-6)',
      step7: 'var(--em-green-7)',
      step8: 'var(--em-green-8)',
      step9: 'var(--em-green-9)',
      step10: 'var(--em-green-10)',
      step11: 'var(--em-green-11)',
      step12: 'var(--em-green-12)',
      contrast: 'var(--em-green-contrast)',
    },
    red: {
      step1: 'var(--em-red-1)',
      step2: 'var(--em-red-2)',
      step3: 'var(--em-red-3)',
      step4: 'var(--em-red-4)',
      step5: 'var(--em-red-5)',
      step6: 'var(--em-red-6)',
      step7: 'var(--em-red-7)',
      step8: 'var(--em-red-8)',
      step9: 'var(--em-red-9)',
      step10: 'var(--em-red-10)',
      step11: 'var(--em-red-11)',
      step12: 'var(--em-red-12)',
      contrast: 'var(--em-red-contrast)',
    },
    amber: {
      step1: 'var(--em-amber-1)',
      step2: 'var(--em-amber-2)',
      step3: 'var(--em-amber-3)',
      step4: 'var(--em-amber-4)',
      step5: 'var(--em-amber-5)',
      step6: 'var(--em-amber-6)',
      step7: 'var(--em-amber-7)',
      step8: 'var(--em-amber-8)',
      step9: 'var(--em-amber-9)',
      step10: 'var(--em-amber-10)',
      step11: 'var(--em-amber-11)',
      step12: 'var(--em-amber-12)',
      contrast: 'var(--em-amber-contrast)',
    },
    blue: {
      step1: 'var(--em-blue-1)',
      step2: 'var(--em-blue-2)',
      step3: 'var(--em-blue-3)',
      step4: 'var(--em-blue-4)',
      step5: 'var(--em-blue-5)',
      step6: 'var(--em-blue-6)',
      step7: 'var(--em-blue-7)',
      step8: 'var(--em-blue-8)',
      step9: 'var(--em-blue-9)',
      step10: 'var(--em-blue-10)',
      step11: 'var(--em-blue-11)',
      step12: 'var(--em-blue-12)',
      contrast: 'var(--em-blue-contrast)',
    },
    orange: {
      step1: 'var(--em-orange-1)',
      step2: 'var(--em-orange-2)',
      step3: 'var(--em-orange-3)',
      step4: 'var(--em-orange-4)',
      step5: 'var(--em-orange-5)',
      step6: 'var(--em-orange-6)',
      step7: 'var(--em-orange-7)',
      step8: 'var(--em-orange-8)',
      step9: 'var(--em-orange-9)',
      step10: 'var(--em-orange-10)',
      step11: 'var(--em-orange-11)',
      step12: 'var(--em-orange-12)',
      contrast: 'var(--em-orange-contrast)',
    },
    purple: {
      step1: 'var(--em-purple-1)',
      step2: 'var(--em-purple-2)',
      step3: 'var(--em-purple-3)',
      step4: 'var(--em-purple-4)',
      step5: 'var(--em-purple-5)',
      step6: 'var(--em-purple-6)',
      step7: 'var(--em-purple-7)',
      step8: 'var(--em-purple-8)',
      step9: 'var(--em-purple-9)',
      step10: 'var(--em-purple-10)',
      step11: 'var(--em-purple-11)',
      step12: 'var(--em-purple-12)',
      contrast: 'var(--em-purple-contrast)',
    },
  },
  space: {
    step0: 'var(--em-space-0)',
    step0_5: 'var(--em-space-0-5)',
    step1: 'var(--em-space-1)',
    step1_5: 'var(--em-space-1-5)',
    step2: 'var(--em-space-2)',
    step2_5: 'var(--em-space-2-5)',
    step3: 'var(--em-space-3)',
    step3_5: 'var(--em-space-3-5)',
    step4: 'var(--em-space-4)',
    step5: 'var(--em-space-5)',
    step6: 'var(--em-space-6)',
    step7: 'var(--em-space-7)',
    step8: 'var(--em-space-8)',
    step10: 'var(--em-space-10)',
    step12: 'var(--em-space-12)',
  },
  radius: {
    default: 'var(--em-radius)',
    xs: 'var(--em-radius-xs)',
    sm: 'var(--em-radius-sm)',
    md: 'var(--em-radius-md)',
    lg: 'var(--em-radius-lg)',
    xl: 'var(--em-radius-xl)',
    twoXl: 'var(--em-radius-2xl)',
    full: 'var(--em-radius-full)',
  },
  typography: {
    family: {
      sans: 'var(--em-font-sans)',
      mono: 'var(--em-font-mono)',
    },
    weight: {
      normal: 'var(--em-font-weight-normal)',
      medium: 'var(--em-font-weight-medium)',
      semibold: 'var(--em-font-weight-semibold)',
    },
    size: {
      micro: 'var(--em-text-micro)',
      tiny: 'var(--em-text-tiny)',
      xs: 'var(--em-text-xs)',
      sm: 'var(--em-text-sm)',
      base: 'var(--em-text-base)',
      lg: 'var(--em-text-lg)',
      xl: 'var(--em-text-xl)',
      twoXl: 'var(--em-text-2xl)',
    },
    lineHeight: {
      micro: 'var(--em-text-micro--line-height)',
      tiny: 'var(--em-text-tiny--line-height)',
      xs: 'var(--em-text-xs--line-height)',
      sm: 'var(--em-text-sm--line-height)',
      base: 'var(--em-text-base--line-height)',
      lg: 'var(--em-text-lg--line-height)',
      xl: 'var(--em-text-xl--line-height)',
      twoXl: 'var(--em-text-2xl--line-height)',
    },
  },
  motion: {
    duration: {
      fast: 'var(--em-motion-duration-fast)',
      normal: 'var(--em-motion-duration-normal)',
      slow: 'var(--em-motion-duration-slow)',
    },
    easing: {
      standard: 'var(--em-motion-easing-standard)',
      emphasized: 'var(--em-motion-easing-emphasized)',
    },
  },
  shadow: {
    sm: 'var(--em-shadow-sm)',
    md: 'var(--em-shadow-md)',
    lg: 'var(--em-shadow-lg)',
    overlay: 'var(--em-shadow-overlay)',
  },
  foreground: {
    default: 'var(--em-foreground)',
    inverse: 'var(--em-foreground-inverse)',
    body: 'var(--em-foreground-body)',
    muted: 'var(--em-foreground-muted)',
    passive: 'var(--em-foreground-passive)',
  },
  border: {
    default: 'var(--em-border)',
    subtle: 'var(--em-border-subtle)',
    muted: 'var(--em-border-1)',
    strong: 'var(--em-border-2)',
    focus: 'var(--em-border-primary)',
    destructive: 'var(--em-border-destructive)',
  },
  surface: {
    current: {
      background: 'var(--em-surface)',
      hover: 'var(--em-surface-hover)',
      selected: 'var(--em-surface-selected)',
      emphasis: 'var(--em-surface-emphasis)',
      emphasisHover: 'var(--em-surface-emphasis-hover)',
      emphasisSelected: 'var(--em-surface-emphasis-selected)',
      input: 'var(--em-surface-input)',
      border: 'var(--em-surface-border)',
      foreground: 'var(--em-surface-foreground)',
    },
    level: {
      sunken: {
        background: 'var(--em-surface-sunken)',
        hover: 'var(--em-surface-sunken-hover)',
        selected: 'var(--em-surface-sunken-selected)',
      },
      base: {
        background: 'var(--em-surface-base)',
        hover: 'var(--em-surface-base-hover)',
        selected: 'var(--em-surface-base-selected)',
      },
      raised: {
        background: 'var(--em-surface-raised)',
        hover: 'var(--em-surface-raised-hover)',
        selected: 'var(--em-surface-raised-selected)',
      },
      elevated: {
        background: 'var(--em-surface-elevated)',
        hover: 'var(--em-surface-elevated-hover)',
        selected: 'var(--em-surface-elevated-selected)',
      },
      overlay: {
        background: 'var(--em-surface-overlay)',
        hover: 'var(--em-surface-overlay-hover)',
        selected: 'var(--em-surface-overlay-selected)',
      },
    },
    role: {
      paper: {
        background: 'var(--em-surface-paper)',
        hover: 'var(--em-surface-paper-hover)',
        selected: 'var(--em-surface-paper-selected)',
      },
    },
    tone: {
      destructive: {
        background: 'var(--em-surface-destructive)',
        hover: 'var(--em-surface-destructive-hover)',
        selected: 'var(--em-surface-destructive-selected)',
        border: 'var(--em-surface-destructive-border)',
        foreground: 'var(--em-surface-destructive-foreground)',
        level: {
          sunken: {
            background: 'var(--em-surface-destructive-sunken)',
            hover: 'var(--em-surface-destructive-sunken-hover)',
            selected: 'var(--em-surface-destructive-sunken-selected)',
            border: 'var(--em-surface-destructive-sunken-border)',
            foreground: 'var(--em-surface-destructive-sunken-foreground)',
          },
          raised: {
            background: 'var(--em-surface-destructive-raised)',
            hover: 'var(--em-surface-destructive-raised-hover)',
            selected: 'var(--em-surface-destructive-raised-selected)',
            border: 'var(--em-surface-destructive-raised-border)',
            foreground: 'var(--em-surface-destructive-raised-foreground)',
          },
          elevated: {
            background: 'var(--em-surface-destructive-elevated)',
            hover: 'var(--em-surface-destructive-elevated-hover)',
            selected: 'var(--em-surface-destructive-elevated-selected)',
            border: 'var(--em-surface-destructive-elevated-border)',
            foreground: 'var(--em-surface-destructive-elevated-foreground)',
          },
          overlay: {
            background: 'var(--em-surface-destructive-overlay)',
            hover: 'var(--em-surface-destructive-overlay-hover)',
            selected: 'var(--em-surface-destructive-overlay-selected)',
            border: 'var(--em-surface-destructive-overlay-border)',
            foreground: 'var(--em-surface-destructive-overlay-foreground)',
          },
        },
        role: {
          paper: {
            background: 'var(--em-surface-destructive-paper)',
            hover: 'var(--em-surface-destructive-paper-hover)',
            selected: 'var(--em-surface-destructive-paper-selected)',
            border: 'var(--em-surface-destructive-paper-border)',
            foreground: 'var(--em-surface-destructive-paper-foreground)',
          },
        },
      },
      warning: {
        background: 'var(--em-surface-warning)',
        hover: 'var(--em-surface-warning-hover)',
        selected: 'var(--em-surface-warning-selected)',
        border: 'var(--em-surface-warning-border)',
        foreground: 'var(--em-surface-warning-foreground)',
        level: {
          sunken: {
            background: 'var(--em-surface-warning-sunken)',
            hover: 'var(--em-surface-warning-sunken-hover)',
            selected: 'var(--em-surface-warning-sunken-selected)',
            border: 'var(--em-surface-warning-sunken-border)',
            foreground: 'var(--em-surface-warning-sunken-foreground)',
          },
          raised: {
            background: 'var(--em-surface-warning-raised)',
            hover: 'var(--em-surface-warning-raised-hover)',
            selected: 'var(--em-surface-warning-raised-selected)',
            border: 'var(--em-surface-warning-raised-border)',
            foreground: 'var(--em-surface-warning-raised-foreground)',
          },
          elevated: {
            background: 'var(--em-surface-warning-elevated)',
            hover: 'var(--em-surface-warning-elevated-hover)',
            selected: 'var(--em-surface-warning-elevated-selected)',
            border: 'var(--em-surface-warning-elevated-border)',
            foreground: 'var(--em-surface-warning-elevated-foreground)',
          },
          overlay: {
            background: 'var(--em-surface-warning-overlay)',
            hover: 'var(--em-surface-warning-overlay-hover)',
            selected: 'var(--em-surface-warning-overlay-selected)',
            border: 'var(--em-surface-warning-overlay-border)',
            foreground: 'var(--em-surface-warning-overlay-foreground)',
          },
        },
        role: {
          paper: {
            background: 'var(--em-surface-warning-paper)',
            hover: 'var(--em-surface-warning-paper-hover)',
            selected: 'var(--em-surface-warning-paper-selected)',
            border: 'var(--em-surface-warning-paper-border)',
            foreground: 'var(--em-surface-warning-paper-foreground)',
          },
        },
      },
      info: {
        background: 'var(--em-surface-info)',
        hover: 'var(--em-surface-info-hover)',
        selected: 'var(--em-surface-info-selected)',
        border: 'var(--em-surface-info-border)',
        foreground: 'var(--em-surface-info-foreground)',
        level: {
          sunken: {
            background: 'var(--em-surface-info-sunken)',
            hover: 'var(--em-surface-info-sunken-hover)',
            selected: 'var(--em-surface-info-sunken-selected)',
            border: 'var(--em-surface-info-sunken-border)',
            foreground: 'var(--em-surface-info-sunken-foreground)',
          },
          raised: {
            background: 'var(--em-surface-info-raised)',
            hover: 'var(--em-surface-info-raised-hover)',
            selected: 'var(--em-surface-info-raised-selected)',
            border: 'var(--em-surface-info-raised-border)',
            foreground: 'var(--em-surface-info-raised-foreground)',
          },
          elevated: {
            background: 'var(--em-surface-info-elevated)',
            hover: 'var(--em-surface-info-elevated-hover)',
            selected: 'var(--em-surface-info-elevated-selected)',
            border: 'var(--em-surface-info-elevated-border)',
            foreground: 'var(--em-surface-info-elevated-foreground)',
          },
          overlay: {
            background: 'var(--em-surface-info-overlay)',
            hover: 'var(--em-surface-info-overlay-hover)',
            selected: 'var(--em-surface-info-overlay-selected)',
            border: 'var(--em-surface-info-overlay-border)',
            foreground: 'var(--em-surface-info-overlay-foreground)',
          },
        },
        role: {
          paper: {
            background: 'var(--em-surface-info-paper)',
            hover: 'var(--em-surface-info-paper-hover)',
            selected: 'var(--em-surface-info-paper-selected)',
            border: 'var(--em-surface-info-paper-border)',
            foreground: 'var(--em-surface-info-paper-foreground)',
          },
        },
      },
      success: {
        background: 'var(--em-surface-success)',
        hover: 'var(--em-surface-success-hover)',
        selected: 'var(--em-surface-success-selected)',
        border: 'var(--em-surface-success-border)',
        foreground: 'var(--em-surface-success-foreground)',
        level: {
          sunken: {
            background: 'var(--em-surface-success-sunken)',
            hover: 'var(--em-surface-success-sunken-hover)',
            selected: 'var(--em-surface-success-sunken-selected)',
            border: 'var(--em-surface-success-sunken-border)',
            foreground: 'var(--em-surface-success-sunken-foreground)',
          },
          raised: {
            background: 'var(--em-surface-success-raised)',
            hover: 'var(--em-surface-success-raised-hover)',
            selected: 'var(--em-surface-success-raised-selected)',
            border: 'var(--em-surface-success-raised-border)',
            foreground: 'var(--em-surface-success-raised-foreground)',
          },
          elevated: {
            background: 'var(--em-surface-success-elevated)',
            hover: 'var(--em-surface-success-elevated-hover)',
            selected: 'var(--em-surface-success-elevated-selected)',
            border: 'var(--em-surface-success-elevated-border)',
            foreground: 'var(--em-surface-success-elevated-foreground)',
          },
          overlay: {
            background: 'var(--em-surface-success-overlay)',
            hover: 'var(--em-surface-success-overlay-hover)',
            selected: 'var(--em-surface-success-overlay-selected)',
            border: 'var(--em-surface-success-overlay-border)',
            foreground: 'var(--em-surface-success-overlay-foreground)',
          },
        },
        role: {
          paper: {
            background: 'var(--em-surface-success-paper)',
            hover: 'var(--em-surface-success-paper-hover)',
            selected: 'var(--em-surface-success-paper-selected)',
            border: 'var(--em-surface-success-paper-border)',
            foreground: 'var(--em-surface-success-paper-foreground)',
          },
        },
      },
    },
  },
  feedback: {
    success: {
      foreground: 'var(--em-foreground-success)',
      background: 'var(--em-background-success)',
      hover: 'var(--em-background-success-hover)',
      border: 'var(--em-border-success)',
    },
    error: {
      foreground: 'var(--em-foreground-error)',
      background: 'var(--em-background-error)',
      hover: 'var(--em-background-error-hover)',
      border: 'var(--em-border-error)',
    },
    warning: {
      foreground: 'var(--em-foreground-warning)',
      background: 'var(--em-background-warning)',
      hover: 'var(--em-background-warning-hover)',
      border: 'var(--em-border-warning)',
    },
    info: {
      foreground: 'var(--em-foreground-info)',
      background: 'var(--em-background-info)',
      hover: 'var(--em-background-info-hover)',
      border: 'var(--em-border-info)',
    },
  },
  selection: {
    background: 'var(--em-selection)',
    foreground: 'var(--em-selection-foreground)',
  },
} as const;

export type Tokens = typeof tokens;
export type TokenReference = `var(--em-${string})`;
