import {
  compileBaseTokenValues,
  compileProfile,
  type ColorSchemeDefinition,
  type DensityProfileDefinition,
  type TypographyProfileDefinition,
} from '../compiler';

export type ThemeProfileDefinitions = Readonly<{
  colorSchemes: readonly ColorSchemeDefinition[];
  densities: readonly DensityProfileDefinition[];
  typographies: readonly TypographyProfileDefinition[];
}>;

function emitVars(
  lines: string[],
  cssVars: Readonly<Record<string, string>>,
  indent: string
): void {
  for (const [property, value] of Object.entries(cssVars)) {
    lines.push(`${indent}${property}: ${value};`);
  }
}

function assertUniqueSelectors(definitions: ThemeProfileDefinitions): void {
  for (const [kind, profiles] of Object.entries(definitions)) {
    const ids = new Set<string>();
    const selectors = new Set<string>();
    for (const profile of profiles) {
      if (ids.has(profile.id)) {
        throw new Error(`${kind} contains duplicate profile id "${profile.id}"`);
      }
      if (selectors.has(profile.selector)) {
        throw new Error(`${kind} contains duplicate profile selector "${profile.selector}"`);
      }
      ids.add(profile.id);
      selectors.add(profile.selector);
    }
  }
}

/** Compile canonical Token Values and emit the public Theme stylesheet. */
export function emitStylesCss(definitions: ThemeProfileDefinitions): string {
  assertUniqueSelectors(definitions);

  const colorSchemes = definitions.colorSchemes.map(compileProfile);
  const densities = definitions.densities.map(compileProfile);
  const typographies = definitions.typographies.map(compileProfile);
  const defaults = [colorSchemes[0], densities[0], typographies[0]];
  if (defaults.some((profile) => profile == null)) {
    throw new Error('Theme Compiler requires at least one profile of every kind');
  }

  const lines = [
    '/* -------------------------------------------',
    ' *  Generated by @emdash/theme Theme Compiler.',
    ' *  DO NOT EDIT — run pnpm build:theme to regenerate.',
    ' * ------------------------------------------- */',
    '',
    '@layer emdash.tokens {',
    '  :root {',
  ];

  emitVars(lines, compileBaseTokenValues(), '    ');
  for (const profile of defaults) {
    emitVars(lines, profile!.cssVars, '    ');
  }
  lines.push('  }', '');

  for (const profile of [...colorSchemes, ...densities, ...typographies]) {
    lines.push(`  ${profile.selector} {`);
    emitVars(lines, profile.cssVars, '    ');
    lines.push('  }', '');
  }

  lines.push('}');
  return lines.join('\n');
}
