/**
 * codegen/emit-theme-css.ts
 *
 * Emits theme/__generated__/theme.css — palette, semantic, shadow, and density
 * token var blocks wrapped in @layer tokens.
 * :root contains vars from the light theme plus the default density; each
 * .em<id> and .density-<id> block overrides its own axis.
 */

import type { ResolvedDensity } from '../define-density';
import type { ResolvedTheme } from '../define-theme';

export function emitThemeCss(themes: ResolvedTheme[], densities: ResolvedDensity[] = []): string {
  const lines: string[] = [
    '/* -------------------------------------------',
    ' *  Generated by packages/ui/src/theme/core/codegen/run.ts',
    ' *  DO NOT EDIT — run pnpm theme:build to regenerate.',
    ' * ------------------------------------------- */',
    '',
  ];

  lines.push('@layer tokens {', '');

  // :root — default vars using the light theme + first density as fallback
  const defaultTheme = themes.find((t) => t.polarity === 'light') ?? themes[0];
  const defaultDensity = densities[0];
  lines.push('  :root {');
  for (const [prop, value] of Object.entries(defaultTheme.cssVars)) {
    lines.push(`    ${prop}: ${value};`);
  }
  if (defaultDensity) {
    for (const [prop, value] of Object.entries(defaultDensity.cssVars)) {
      lines.push(`    ${prop}: ${value};`);
    }
  }
  lines.push('  }', '');

  // Per-theme selectors
  for (const theme of themes) {
    lines.push(`  ${theme.selector} {`);
    for (const [prop, value] of Object.entries(theme.cssVars)) {
      lines.push(`    ${prop}: ${value};`);
    }
    lines.push('  }', '');
  }

  // Per-density selectors
  for (const density of densities) {
    lines.push(`  ${density.selector} {`);
    for (const [prop, value] of Object.entries(density.cssVars)) {
      lines.push(`    ${prop}: ${value};`);
    }
    lines.push('  }', '');
  }

  lines.push('}');
  return lines.join('\n');
}
