export const WORKSPACE_IGNORED_DIR_NAMES = [
  '.svn',
  '.hg',
  '.git',
  'node_modules',
  'dist',
  'build',
  '.next',
  '.nuxt',
  'coverage',
  '.cache',
  '.parcel-cache',
  '__pycache__',
  '.pytest_cache',
  'venv',
  '.venv',
  'target',
  '.terraform',
  '.serverless',
  'worktrees',
  '.emdash',
  '.conductor',
  '.cursor',
  '.claude',
  '.devin',
  '.amp',
  '.codex',
  '.aider',
  '.continue',
  '.cody',
  '.windsurf',
] as const;

export const WORKSPACE_IGNORED_DIRS = new Set<string>(WORKSPACE_IGNORED_DIR_NAMES);
