import { defineConfig } from 'tsdown';

export default defineConfig({
  entry: {
    'primitives-path-api': 'src/primitives/path/api/index.ts',
    'primitives-host-api': 'src/primitives/host/api/index.ts',
    'primitives-lib-api': 'src/primitives/lib/api/index.ts',
    'primitives-concurrency-api': 'src/primitives/concurrency/api/index.ts',
    'primitives-workflow-api': 'src/primitives/workflow/api/index.ts',
    'primitives-skills-api': 'src/primitives/skills/api/index.ts',
    'primitives-mcp-api': 'src/primitives/mcp/api/index.ts',
    'primitives-acp-transcript-api': 'src/primitives/acp-transcript/api/index.ts',
    'primitives-exec-api': 'src/primitives/exec/api/index.ts',
    'primitives-host-dependencies-api': 'src/primitives/host-dependencies/api/index.ts',
    'primitives-kv-api': 'src/primitives/kv/api/index.ts',
    'primitives-io-activity-api': 'src/primitives/io-activity/api/index.ts',
    'primitives-kv-node': 'src/primitives/kv/node/index.ts',
    'primitives-agent-env-api': 'src/primitives/agent-env/api/index.ts',
    'primitives-plugin-fs-api': 'src/primitives/plugin-fs/api/index.ts',
    'primitives-versioned-schema-api': 'src/primitives/versioned-schema/api/index.ts',
    'primitives-sqlite-store-api': 'src/primitives/sqlite-store/api/index.ts',
    'primitives-sqlite-store-node': 'src/primitives/sqlite-store/node/index.ts',
    'primitives-sqlite-store-testing': 'src/primitives/sqlite-store/testing/index.ts',
    'services-exec-api': 'src/services/exec/api/index.ts',
    'services-exec-node': 'src/services/exec/node/index.ts',
    'services-pty-api': 'src/services/pty/api/index.ts',
    'services-pty-node': 'src/services/pty/node/index.ts',
    'services-host-dependencies-api': 'src/services/host-dependencies/api/index.ts',
    'services-host-dependencies-node': 'src/services/host-dependencies/node/index.ts',
    'services-agent-plugins-api': 'src/services/agent-plugins/api/index.ts',
    'services-agent-plugins-api-plugins': 'src/services/agent-plugins/api/plugins/index.ts',
    'services-agent-plugins-api-plugins-helpers':
      'src/services/agent-plugins/api/plugins/helpers/index.ts',
    'services-agent-plugins-api-spawn-context': 'src/services/agent-plugins/api/spawn-context.ts',
    'services-session-intents-api': 'src/services/session-intents/api/index.ts',
    'services-session-intents-node': 'src/services/session-intents/node/index.ts',
    'services-fs-watch-api': 'src/services/fs-watch/api/index.ts',
    'services-fs-watch-node': 'src/services/fs-watch/node/index.ts',
    'services-script-workflows-api': 'src/services/script-workflows/api/index.ts',
    'runtimes-git-api': 'src/runtimes/git/api/index.ts',
    'runtimes-git-node': 'src/runtimes/git/node/index.ts',
    'runtimes-files-api': 'src/runtimes/files/api/index.ts',
    'runtimes-files-node': 'src/runtimes/files/node/index.ts',
    'runtimes-file-search-api': 'src/runtimes/file-search/api/index.ts',
    'runtimes-file-search-node': 'src/runtimes/file-search/node/index.ts',
    'runtimes-acp-api': 'src/runtimes/acp/api/index.ts',
    'runtimes-acp-api-client': 'src/runtimes/acp/api/client.ts',
    'runtimes-acp-node': 'src/runtimes/acp/node/index.ts',
    'runtimes-agent-config-api': 'src/runtimes/agent-config/api/index.ts',
    'runtimes-agent-config-node': 'src/runtimes/agent-config/node/index.ts',
    'runtimes-automations-api': 'src/runtimes/automations/api/index.ts',
    'runtimes-tui-agents-api': 'src/runtimes/tui-agents/api/index.ts',
    'runtimes-tui-agents-node': 'src/runtimes/tui-agents/node/index.ts',
    'runtimes-terminals-api': 'src/runtimes/terminals/api/index.ts',
    'runtimes-terminals-node': 'src/runtimes/terminals/node/index.ts',
    'runtimes-workspace-api': 'src/runtimes/workspace/api/index.ts',
    'runtimes-workspace-node': 'src/runtimes/workspace/node/index.ts',
    'workspace-server': 'src/workspace-server/index.ts',
    'workspace-server-wire': 'src/workspace-server/wire/index.ts',
  },
  format: ['esm'],
  dts: true,
  deps: {
    neverBundle: [
      '@agentclientprotocol/sdk',
      '@emdash/shared',
      '@emdash/wire',
      '@parcel/watcher',
      'glob',
      'node-pty',
      'react',
      'semver',
      'smol-toml',
      'zod',
    ],
  },
  sourcemap: true,
  clean: true,
});
