import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { compileDrizzleSchemaToSql } from '@emdash/core/primitives/sqlite-store/codegen';
import { fingerprintDerivedSchema } from '@emdash/core/primitives/sqlite-store/node';
import { format } from 'oxfmt';
import * as schema from '../src/core/services/pull-requests/node/store/schema';

const statements = await compileDrizzleSchemaToSql(schema);
const fingerprint = fingerprintDerivedSchema(statements);
const outputPath = fileURLToPath(
  new URL('../src/core/services/pull-requests/node/store/schema-sql.generated.ts', import.meta.url)
);

const source = `// Generated by scripts/generate-pr-schema.ts. Do not edit manually.
export const schemaSqlStatements = ${JSON.stringify(statements, null, 2)} as const;

export const schemaFingerprint = ${fingerprint};
`;

const formatted = await format(outputPath, source, {
  printWidth: 100,
  singleQuote: true,
  semi: true,
  trailingComma: 'es5',
});
if (formatted.errors.length > 0) {
  throw new Error(`Unable to format generated PR schema: ${formatted.errors.join(', ')}`);
}
await writeFile(outputPath, formatted.code, 'utf8');
