import { z } from 'zod';

export const terminalExitSchema = z.object({
  exitCode: z.number().int().nullable(),
  signal: z.string().nullable(),
});
export type TerminalExit = z.infer<typeof terminalExitSchema>;

/**
 * Serializable snapshot of a managed terminal's lifecycle metadata.
 * Returned by AcpRuntime.getTerminals() so that a renderer reload
 * can hydrate the full terminal list from the main-process authority without
 * replaying any event stream.
 *
 * Deliberately carries no output text: the per-terminal log stream
 * (AcpRuntime.terminalOutputLog) is the only output-text path to clients.
 */
export const terminalStateSchema = z.object({
  /** Stable id generated by the runtime for this terminal. */
  terminalId: z.string(),
  /** The command that was executed. */
  command: z.string(),
  /** Arguments passed to the command. */
  args: z.array(z.string()),
  /** Working directory the command ran in. */
  cwd: z.string(),
  /** True when output was truncated due to the agent-side outputByteLimit cap. */
  truncated: z.boolean(),
  /** Non-null once the command has exited. */
  exitStatus: terminalExitSchema.nullable(),
});
export type TerminalState = z.infer<typeof terminalStateSchema>;
export const terminalSnapshotSchema = terminalStateSchema;
export type TerminalSnapshot = TerminalState;
