// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	/**  Login-shell `$PATH` captured at app startup. OnceLock-cached. */
	getPath: () => __TAURI_INVOKE<string>("get_path"),
};

