// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	/**  Login-shell `$PATH` captured at app startup. OnceLock-cached. */
	getPath: () => __TAURI_INVOKE<string>("get_path"),
	setSecret: (key: string, value: string) => typedError<null, SecretsCommandError>(__TAURI_INVOKE("set_secret", { key, value })),
	getSecret: (key: string) => typedError<string | null, SecretsCommandError>(__TAURI_INVOKE("get_secret", { key })),
	ptySpawn: (opts: SpawnOptions, onData: Channel<number[]>) => typedError<PtyId, PtyError>(__TAURI_INVOKE("pty_spawn", { opts, onData })),
	ptyWrite: (id: PtyId, bytes: number[]) => typedError<null, PtyError>(__TAURI_INVOKE("pty_write", { id, bytes })),
	ptyResize: (id: PtyId, size: PtySize) => typedError<null, PtyError>(__TAURI_INVOKE("pty_resize", { id, size })),
	ptyKill: (id: PtyId) => typedError<null, PtyError>(__TAURI_INVOKE("pty_kill", { id })),
};

/* Types */
export type PtyError = { kind: "not_found"; id: PtyId } | { kind: "spawn_failed"; message: string } | { kind: "io"; message: string };

export type PtyId = number;

export type PtySize = {
	rows: number,
	cols: number,
};

export type SecretsCommandError = {
	/**  Stable machine-readable identifier. Renderer matches on this. */
	code: SecretsErrorCode,
	/**  Human-readable hint. Surface this to the user verbatim. */
	message: string,
};

export type SecretsErrorCode = "keyring_unavailable" | "crypto" | "storage" | "invalid_value" | "unknown";

export type SpawnOptions = {
	command: string,
	args: string[],
	cwd: string | null,
	env: { [key in string]: string },
	size: PtySize,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

